package family.dd.DDHomeKits.AuthCenter.domain.UserAuthentication.entity;


import static family.dd.DDHomeKits.AuthCenter.infrastructure.util.CommonUtil.isNull;

/**
 * Define user privileges
 * Use bit position of a {@link long} value to identify user authorities
 */
public enum Privilege {
    LOG_IN(1, "Log in"),
    USER_MANAGE(2, "Manage Users"),
    SYSTEM_ADMIN(30, "Manage System"),
    EXTENSION(31, "Reserved field");

    /**
     *  Value scope 1~31
     */
    private int bitPosition;
    private String description;

    Privilege(int bitPosition, String description){
        this.bitPosition = bitPosition;
        this.description = description;
    }
    /**
     * Returns authority in {@link long} value.
     *
     * @param privileges some privilege
     *
     * @return a {@link long} value with specified bit position, 0L if no privilege is passed.
     */
    public static long toLongValue(Privilege...privileges){
        long authority = 0L;
        if (isNull(privileges)) {
            return authority;
        }
        for (Privilege privilege : privileges) {
            authority = authority|(1<<(privilege.bitPosition-1));
        }
        return authority;
    }

    /**
     * @param authority {@link long} value generated by {@link #toLongValue(Privilege...)}
     * @param privileges defined in {@link Privilege}
     * @return {@code true} if authority contains privileges
     */
    public static boolean hasPermission(long authority, Privilege...privileges){
        long longValueAuth = toLongValue(privileges);
        return longValueAuth == (longValueAuth & authority);
    }
}
